### ISSUE TITLE
Qt3

### ISSUE THREAD

**Issue by cadik** [cadik/TMS#10]
The gui part of the project (TMOgui) has been implemented in Qt3. We need to port it to Qt5.

**Comment by cadik** [comment]
Any volunteer to do this?

**Comment by kkofler** [comment]
Please note that this is required for the GUI to work at all, because OpenCV is linked against Qt 5 and crashes if you attempt to use it together with Qt 3.

**Comment by Jedlic** [comment]
This should be solved by pull request #100

**Comment by cadik** [comment]
Yes, this shall be now solved.
