### ISSUE TITLE
wrong histogram range for saving image -> unusable tmocmd

### ISSUE THREAD

**Issue by freetomik** [cadik/TMS#83]
Transformed images are saved with wrong histogram range. After transforming by some tone mapping operator, histogram range of image is set to interval <0,1>.
![tms_hist_bug](https://user-images.githubusercontent.com/5520368/52561821-c9abd180-2dfc-11e9-81da-cb53edefae0e.png)
However, transform operators mostly do not output images in range <0,1>. This leads to changing of image luminance/color range, when it is being saved.

In TMOGui, user can change histogram to desired range and save image within that range. But no such option for changing histogram range is available in TMOCmd, which is also affected by this bug and it makes it unusable.

**Comment by freetomik** [comment]
I looked into code for tmocmd case, and path through code is:
```
TMOCmd.cpp:
  Transform()
  Convert(TMO_RGB)
  SaveWithSuffix(imgname)
    TMOImage.cpp:
      SaveAs(...)
        Save(...)
          SaveTIFF_8()
            WriteHeader(...)
            WriteData(...)
```
But I'm not sure, where the histogram clipping occurs.
Image from example operator `Ward94` called with `Transform()` is in RGB format, so `Convert(TMO_RGB)` does nothing in this case.
In following saving methods I didn't noticed anything about histogram range change.

TMOCmd is very useful for using in scripts.
Any help appreciated.

**Comment by cadik** [comment]
The plugin output is supposed to be in range [0,1].

**Comment by freetomik** [comment]
Ok, this is an important missing piece of information, at least for me.
More plugins does not respect that. I will create another issue for that.
